name: 'Bumpversion'
on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: Bumping version
    steps:
      - name: Try bump
        uses: Clinical-Genomics/bump2version-ci@master
        with:
          repository: "https://github.com/Clinical-Genomics/bump2version-ci.git"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}