name: 'Bump2version-CI'
on:
  push:
    branches:
      - 'master'
      - 'main'
jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: Bump version and push tags to master
    steps:
      - name: Bump version
        uses: Mropat/bump2version-action@main
        env:
          BUMPVERSION_TOKEN: ${{ secrets.BUMPVERSION_TOKEN }}
          BUMPVERSION_AUTHOR: ${{ secrets.BUMPVERSION_AUTHOR }}
          GITHUB_REPOSITORY: ${{ github.repository }}
