name: Releases

on:
  workflow_run:
    workflows: [ "Bump2version-CI" ]
    types: [ completed ]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

